targets += dtbs
dtbs: $(addprefix $(obj)/, $(DTB_LIST))

dtb-$(CONFIG_MACH_EXYNOS7870_J7TOPLTE_KOR) := \
	exynos7870-j7toplte_kor_skt_00.dtb \
	exynos7870-j7toplte_kor_skt_01.dtb \
	exynos7870-j7toplte_kor_skt_02.dtb \
	exynos7870-j7toplte_kor_skt_03.dtb \
	exynos7870-j7toplte_kor_skt_04.dtb
 
clean-files := dts/*.dtb *.dtb*
